In [14]:
import pandas as pd, seaborn as sb, matplotlib.pyplot as mpl, plotly as pl, numpy as np
from statsmodels.graphics.mosaicplot import mosaic as mos

In [15]:
# Here we will visualize the average distribution of sales in terms of items sold per day of the week. Each vertical column is a day of the week. The space each block takes up in a column represents the relative demand of that item compared to the others in that day. I will also label total items sold per day.

In [55]:
wk_0 = '../the_tang/week_0_items.csv'

df = pd.read_csv(str(wk_0))

In [56]:
display(df)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Thu 02/01/2018,Unnamed: 8,Fri 02/02/2018,...,Wed 02/07/2018,Unnamed: 20,Thu 02/08/2018,Unnamed: 22,Fri 02/09/2018,Unnamed: 24,Sat 02/10/2018,Unnamed: 26,Sun 02/11/2018,Unnamed: 28
0,Class,Name,Parent Product,SKU,Barcode,Category,Subcategory,Quantity,Total,Quantity,...,Quantity,Total,Quantity,Total,Quantity,Total,Quantity,Total,Quantity,Total
1,Beverage,Apple Soda - 蘋果西打,NaN,NaN,100000000199,Drinks,Soft Drinks,3,7.50,3,...,1,2.50,3,7.50,NaN,NaN,1,2.50,NaN,NaN
2,Beverage,Coke - 可乐,NaN,NaN,100000000236,Drinks,Soft Drinks,2,4.00,3,...,1,2.00,3,6.00,3,6.00,NaN,NaN,NaN,NaN
3,Beverage,Diet Coke - 健怡可乐,NaN,NaN,100000000243,Drinks,Soft Drinks,NaN,NaN,NaN,...,NaN,NaN,2,4.00,NaN,NaN,NaN,NaN,NaN,NaN
4,Beverage,Plum Juice - 酸梅汤,NaN,NaN,100000000205,Drinks,Soft Drinks,1,3.00,1,...,NaN,NaN,2,6.00,2,6.00,3,9.00,NaN,NaN
5,Beverage,Sprite - 雪碧,NaN,NaN,100000000267,Drinks,Soft Drinks,1,2.00,6,...,NaN,NaN,1,2.00,NaN,NaN,NaN,NaN,NaN,NaN
6,Extra Items,Beer cork fee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,10.00,NaN,NaN,NaN,NaN
7,Food,Braised Beef Noodle Soup - 麻辣牛腩面,NaN,NaN,100000001042,Noodles,Noodles,8,120.00,25,...,9,135.00,12,180.00,20,300.00,20,300.00,NaN,NaN
8,Food,DDM - 擔擔麵,NaN,NaN,100000000434,Noodles,Noodles,11,123.00,7,...,4,44.00,6,66.00,8,90.00,NaN,NaN,NaN,NaN
9,Food,Drunk Noodles - 醉面,NaN,NaN,100000000335,Noodles,Noodles,24,325.50,32,...,18,243.00,13,175.50,29,396.00,8,109.50,NaN,NaN
10,Food,Extra Beef,NaN,NaN,100000000380,Appetizer,A La Carte Meats,NaN,NaN,NaN,...,NaN,NaN,1,3.00,NaN,NaN,NaN,NaN,NaN,NaN
11,Food,Extra Pork,NaN,NaN,100000000373,Appetizer,A La Carte Meats,1,2.00,NaN,...,6,12.00,NaN,NaN,6,12.00,NaN,NaN,NaN,NaN
12,Food,MJM - 麻酱面,NaN,0009,000000000009,Noodles,Noodles,1,11.00,4,...,2,22.00,2,22.00,3,36.00,1,11.00,NaN,NaN
13,Food,PB&SB Steamed Noodles -五花豆角焖面,NaN,0010,000000000010,Noodles,Noodles,5,67.50,13,...,7,94.50,9,121.50,23,310.50,2,27.00,NaN,NaN
14,Food,Sesame Tofu - 胡麻豆腐,NaN,0006,000000000006,Appetizer,Cold,10,50.00,6,...,5,25.00,3,15.00,8,40.00,6,30.00,NaN,NaN
15,Food,Sizzling Noodles - 油泼面,NaN,0013,000000000013,Noodles,Noodles,4,48.00,10,...,7,87.00,4,48.00,14,177.00,6,74.00,NaN,NaN
16,Food,Sliced Beef Shanks - 酱牛肉,NaN,0004,000000000004,Appetizer,Cold,6,42.00,3,...,2,14.00,1,7.00,7,49.00,2,14.00,NaN,NaN
17,Food,Soft Boiled Egg - 糖心蛋,NaN,0001,000000000001,Appetizer,Cold,NaN,NaN,2,...,1,1.50,2,3.00,2,3.00,1,1.50,NaN,NaN
18,Food,ZJM - 炸酱面,NaN,0008,000000000008,Noodles,Noodles,6,72.00,15,...,4,48.00,13,156.00,14,168.00,7,84.00,NaN,NaN
19,Unknown Class,Braised beef soup,NaN,NaN,100000001080,Noodles,Extra,NaN,NaN,NaN,...,1,5.00,1,5.00,NaN,NaN,1,5.00,NaN,NaN
20,Unknown Class,Extra Thick Noodles,NaN,NaN,100000000748,Noodles,Extra,NaN,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Unknown Class,Extra Thin Noodles,NaN,NaN,100000000755,Noodles,Extra,1,2.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Unknown Class,Fried Pork Buns - 猪肉包,NaN,NaN,100000000991,Appetizer,Hot,3,24.00,19,...,4,32.00,5,40.00,11,88.00,2,16.00,NaN,NaN
23,Unknown Class,Fried Turnip Cake - 蘿蔔糕,NaN,NaN,100000000489,Appetizer,Hot,5,25.00,12,...,2,10.00,7,35.00,5,25.00,NaN,NaN,NaN,NaN
24,Unknown Class,Garlic Pork Dumplings - 蒜香豬肉餃,NaN,NaN,100000000496,Appetizer,Hot,6,48.00,9,...,8,64.00,5,40.00,17,136.00,9,72.00,NaN,NaN
25,Unknown Class,Ginjo Oka Bottle,NaN,NaN,100000000908,Drinks,Sake,2,36.00,2,...,NaN,NaN,NaN,NaN,1,18.00,NaN,NaN,NaN,NaN
26,Unknown Class,Ginjo Oka glass,NaN,NaN,100000001103,Drinks,Sake,2,16.00,3,...,NaN,NaN,NaN,NaN,NaN,NaN,2,16.00,NaN,NaN
27,Unknown Class,House Sake Bottle,NaN,NaN,100000000892,Drinks,Sake,2,72.00,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Unknown Class,House Sake Glass,NaN,NaN,100000000885,Drinks,Sake,NaN,NaN,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Unknown Class,Jala Beef Shanks - 酸辣牛肉,NaN,NaN,100000000441,Appetizer,Cold,NaN,NaN,2,...,3,24.00,3,24.00,3,24.00,1,8.00,NaN,NaN
30,Unknown Class,Lychee,NaN,NaN,100000000977,Dessert,Ice Cream,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Unknown Class,Mexican Coke,NaN,NaN,100000000847,Drinks,Soft Drinks,NaN,NaN,NaN,...,NaN,NaN,1,3.00,1,3.00,NaN,NaN,NaN,NaN
32,Unknown Class,Naughty Tofu - 皮蛋豆腐,NaN,NaN,100000000557,Appetizer,Cold,4,28.00,7,...,NaN,NaN,3,21.00,4,28.00,1,7.00,NaN,NaN
33,Unknown Class,Oxtail Noodle Soup -骨汤牛尾面,NaN,NaN,100000001059,Noodles,Noodles,3,40.50,3,...,1,13.50,4,57.00,9,121.50,2,27.00,NaN,NaN
34,Unknown Class,Oxtail soup,NaN,NaN,100000001073,Noodles,Extra,1,3.00,2,...,NaN,NaN,1,3.00,1,3.00,NaN,NaN,NaN,NaN
35,Unknown Class,Plum sake glass,NaN,NaN,100000001097,Drinks,Sake,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Unknown Class,Scallion Pancake - 蔥油餅,NaN,NaN,100000000700,Appetizer,Hot,3,21.00,6,...,3,21.00,5,35.00,2,14.00,2,14.00,NaN,NaN
37,Unknown Class,Shredded Potato Salad - 涼拌土豆絲,NaN,NaN,100000000564,Appetizer,Cold,2,10.00,6,...,NaN,NaN,2,10.00,4,20.00,2,10.00,NaN,NaN
38,Unknown Class,Taiwan,NaN,NaN,100000000793,Drinks,Beer,5,30.00,7,...,3,18.00,1,6.00,5,30.00,NaN,NaN,NaN,NaN
39,Unknown Class,Taro,NaN,NaN,100000000984,Dessert,Ice Cream,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Unknown Class,Tiger,NaN,100000000922,100000000915,Drinks,Beer,2,12.00,4,...,NaN,NaN,NaN,NaN,1,6.00,NaN,NaN,NaN,NaN
41,Unknown Class,Tsingtao,NaN,NaN,100000000779,Drinks,Beer,4,20.00,8,...,3,15.00,1,5.00,13,65.00,1,5.00,NaN,NaN
42,Unknown Class,Wang Lao Ji Herbal Tea - 王老吉,NaN,NaN,100000000229,Drinks,Soft Drinks,1,2.00,1,...,1,2.00,NaN,NaN,3,6.00,3,6.00,NaN,NaN
43,Unknown Class,Yuzu Sake Glass,NaN,NaN,100000001035,Drinks,Sake,NaN,NaN,0,...,NaN,NaN,NaN,NaN,1,8.00,NaN,NaN,NaN,NaN

In [57]:
# Iterate through day, manually due to nature of data:

item_dictionary = []
line = 0
for index, row in df.iterrows():
    item_dictionary.append([row[1],[]])
    for i in range(0,7):
        col = 7 + (i*2)
        item_dictionary[line][1].append(row[col])
    line += 1

In [58]:
item_dictionary.pop(0)
display(item_dictionary)

[['Apple Soda - 蘋果西打', ['3', '3', '4', '2', '2', '3', '1']],
 ['Coke - 可乐', ['2', '3', '1', '1', '2', nan, '1']],
 ['Diet Coke - 健怡可乐', [nan, nan, '2', '2', nan, '1', nan]],
 ['Plum Juice - 酸梅汤', ['1', '1', '4', '6', '4', '3', nan]],
 ['Sprite - 雪碧', ['1', '6', nan, '1', nan, nan, nan]],
 ['Beer cork fee', [nan, nan, nan, nan, nan, nan, nan]],
 ['Braised Beef Noodle Soup - 麻辣牛腩面',
  ['8', '25', '40', '14', '14', '13', '9']],
 ['DDM - 擔擔麵', ['11', '7', '7', '5', '3', '4', '4']],
 ['Drunk Noodles - 醉面', ['24', '32', '41', '22', '16', '20', '18']],
 ['Extra Beef', [nan, nan, nan, nan, nan, nan, nan]],
 ['Extra Pork', ['1', nan, '8', '1', nan, '8', '6']],
 ['MJM - 麻酱面', ['1', '4', '3', '3', nan, '2', '2']],
 ['PB&SB Steamed Noodles -五花豆角焖面', ['5', '13', '22', '11', '10', '3', '7']],
 ['Sesame Tofu - 胡麻豆腐', ['10', '6', '15', '6', '3', '2', '5']],
 ['Sizzling Noodles - 油泼面', ['4', '10', '17', '12', '5', '7', '7']],
 ['Sliced Beef Shanks - 酱牛肉', ['6', '3', '3', '1', nan, nan, '2']],
 ['Soft Boiled Egg - 糖心蛋', [nan, '2', '6', '8', '1', nan, '1']],
 ['ZJM - 炸酱面', ['6', '15', '24', '7', '3', '7', '4']],
 ['Braised beef soup', [nan, nan, '3', '1', nan, nan, '1']],
 ['Extra Thick Noodles', [nan, '1', nan, nan, nan, nan, nan]],
 ['Extra Thin Noodles', ['1', nan, nan, nan, nan, nan, nan]],
 ['Fried Pork Buns - 猪肉包', ['3', '19', '14', '10', '6', '2', '4']],
 ['Fried Turnip Cake - 蘿蔔糕', ['5', '12', '9', '4', '2', '4', '2']],
 ['Garlic Pork Dumplings - 蒜香豬肉餃', ['6', '9', '11', '12', '7', '5', '8']],
 ['Ginjo Oka Bottle', ['2', '2', '2', nan, nan, nan, nan]],
 ['Ginjo Oka glass', ['2', '3', '1', '1', nan, nan, nan]],
 ['House Sake Bottle', ['2', '1', nan, nan, nan, nan, nan]],
 ['House Sake Glass', [nan, '3', nan, nan, nan, nan, nan]],
 ['Jala Beef Shanks - 酸辣牛肉', [nan, '2', '5', '1', '5', '2', '3']],
 ['Lychee', [nan, nan, '1', nan, nan, nan, nan]],
 ['Mexican Coke', [nan, nan, '1', nan, nan, nan, nan]],
 ['Naughty Tofu - 皮蛋豆腐', ['4', '7', '4', '5', '4', '2', nan]],
 ['Oxtail Noodle Soup -骨汤牛尾面', ['3', '3', '5', '7', '2', '4', '1']],
 ['Oxtail soup', ['1', '2', '2', '4', '1', '1', nan]],
 ['Plum sake glass', [nan, nan, '1', nan, nan, nan, nan]],
 ['Scallion Pancake - 蔥油餅', ['3', '6', '13', '8', '1', '3', '3']],
 ['Shredded Potato Salad - 涼拌土豆絲', ['2', '6', '6', '2', '1', nan, nan]],
 ['Taiwan', ['5', '7', '2', nan, '2', nan, '3']],
 ['Taro', [nan, nan, nan, '1', nan, nan, nan]],
 ['Tiger', ['2', '4', '3', nan, '1', '2', nan]],
 ['Tsingtao', ['4', '8', '5', '1', '1', nan, '3']],
 ['Wang Lao Ji Herbal Tea - 王老吉', ['1', '1', '3', '2', '2', '2', '1']],
 ['Yuzu Sake Glass', [nan, '0', nan, nan, nan, nan, nan]]]

In [69]:
days_data = ({})
totals = []

weekdays = []

for i in range(0,7):
    weekdays.append([])
    for item in item_dictionary:
            if not isinstance(item[1][i], str):
                item[1][i] = 0
#             for j in range(i,int(item[1][i])):
            weekdays[i].append(item[1][i])


dict = { 'Mon': weekdays[0],
        'Tue': weekdays[1],
        'Wed': weekdays[2],
        'Thu': weekdays[3],
        'Fri': weekdays[4],
        'Sat': weekdays[5],
        'Sun': weekdays[6],
       }

display(dict)
data = pandas.DataFrame(dict)
display(data)

{'Fri': ['2',
  '2',
  0,
  '4',
  0,
  0,
  '14',
  '3',
  '16',
  0,
  0,
  0,
  '10',
  '3',
  '5',
  0,
  '1',
  '3',
  0,
  0,
  0,
  '6',
  '2',
  '7',
  0,
  0,
  0,
  0,
  '5',
  0,
  0,
  '4',
  '2',
  '1',
  0,
  '1',
  '1',
  '2',
  0,
  '1',
  '1',
  '2',
  0],
 'Mon': ['3',
  '2',
  0,
  '1',
  '1',
  0,
  '8',
  '11',
  '24',
  0,
  '1',
  '1',
  '5',
  '10',
  '4',
  '6',
  0,
  '6',
  0,
  0,
  '1',
  '3',
  '5',
  '6',
  '2',
  '2',
  '2',
  0,
  0,
  0,
  0,
  '4',
  '3',
  '1',
  0,
  '3',
  '2',
  '5',
  0,
  '2',
  '4',
  '1',
  0],
 'Sat': ['3',
  0,
  '1',
  '3',
  0,
  0,
  '13',
  '4',
  '20',
  0,
  '8',
  '2',
  '3',
  '2',
  '7',
  0,
  0,
  '7',
  0,
  0,
  0,
  '2',
  '4',
  '5',
  0,
  0,
  0,
  0,
  '2',
  0,
  0,
  '2',
  '4',
  '1',
  0,
  '3',
  0,
  0,
  0,
  '2',
  0,
  '2',
  0],
 'Sun': ['1',
  '1',
  0,
  0,
  0,
  0,
  '9',
  '4',
  '18',
  0,
  '6',
  '2',
  '7',
  '5',
  '7',
  '2',
  '1',
  '4',
  '1',
  0,
  0,
  '4',
  '2',
  '8',
  0,
  0,
  0,
  0,
  '3',
  0,
  0,
  0,
  '1',
  0,
  0,
  '3',
  0,
  '3',
  0,
  0,
  '3',
  '1',
  0],
 'Thu': ['2',
  '1',
  '2',
  '6',
  '1',
  0,
  '14',
  '5',
  '22',
  0,
  '1',
  '3',
  '11',
  '6',
  '12',
  '1',
  '8',
  '7',
  '1',
  0,
  0,
  '10',
  '4',
  '12',
  0,
  '1',
  0,
  0,
  '1',
  0,
  0,
  '5',
  '7',
  '4',
  0,
  '8',
  '2',
  0,
  '1',
  0,
  '1',
  '2',
  0],
 'Tue': ['3',
  '3',
  0,
  '1',
  '6',
  0,
  '25',
  '7',
  '32',
  0,
  0,
  '4',
  '13',
  '6',
  '10',
  '3',
  '2',
  '15',
  0,
  '1',
  0,
  '19',
  '12',
  '9',
  '2',
  '3',
  '1',
  '3',
  '2',
  0,
  0,
  '7',
  '3',
  '2',
  0,
  '6',
  '6',
  '7',
  0,
  '4',
  '8',
  '1',
  '0'],
 'Wed': ['4',
  '1',
  '2',
  '4',
  0,
  0,
  '40',
  '7',
  '41',
  0,
  '8',
  '3',
  '22',
  '15',
  '17',
  '3',
  '6',
  '24',
  '3',
  0,
  0,
  '14',
  '9',
  '11',
  '2',
  '1',
  0,
  0,
  '5',
  '1',
  '1',
  '4',
  '5',
  '2',
  '1',
  '13',
  '6',
  '2',
  0,
  '3',
  '5',
  '3',
  0]}

   Fri Mon Sat Sun Thu Tue Wed
0    2   3   3   1   2   3   4
1    2   2   0   1   1   3   1
2    0   0   1   0   2   0   2
3    4   1   3   0   6   1   4
4    0   1   0   0   1   6   0
5    0   0   0   0   0   0   0
6   14   8  13   9  14  25  40
7    3  11   4   4   5   7   7
8   16  24  20  18  22  32  41
9    0   0   0   0   0   0   0
10   0   1   8   6   1   0   8
11   0   1   2   2   3   4   3
12  10   5   3   7  11  13  22
13   3  10   2   5   6   6  15
14   5   4   7   7  12  10  17
15   0   6   0   2   1   3   3
16   1   0   0   1   8   2   6
17   3   6   7   4   7  15  24
18   0   0   0   1   1   0   3
19   0   0   0   0   0   1   0
20   0   1   0   0   0   0   0
21   6   3   2   4  10  19  14
22   2   5   4   2   4  12   9
23   7   6   5   8  12   9  11
24   0   2   0   0   0   2   2
25   0   2   0   0   1   3   1
26   0   2   0   0   0   1   0
27   0   0   0   0   0   3   0
28   5   0   2   3   1   2   5
29   0   0   0   0   0   0   1
30   0   0   0   0   0   0   1
31   4   4   2   0   5   7   4
32   2   3   4   1   7   3   5
33   1   1   1   0   4   2   2
34   0   0   0   0   0   0   1
35   1   3   3   3   8   6  13
36   1   2   0   0   2   6   6
37   2   5   0   3   0   7   2
38   0   0   0   0   1   0   0
39   1   2   2   0   0   4   3
40   1   4   0   3   1   8   5
41   2   1   2   1   2   1   3
42   0   0   0   0   0   0   0

In [73]:
mos(data,[0])

KeyError: '[0] not in index'